"""Shared typed schema boundary for pipeline components."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Literal


@dataclass(frozen=True)
class DataLayoutReport:
    """Summary of a validated official Multimodal data layout."""

    data_root: Path
    train_rows: int
    test_rows: int
    sample_submission_rows: int


@dataclass(frozen=True)
class SampleRecord:
    """Typed record parsed from one official Multimodal test.csv row."""

    sample_id: str
    image_path: Path
    context: str
    question: str
    answers: tuple[str, str, str]
    row_number: int


EvidenceType = Literal[
    "stated_text_fact",
    "objective_visible_evidence",
    "elimination",
    "insufficient_evidence",
]
ReasonerLabel = Literal["0", "1", "2"]
ReasonerRiskFlag = Literal["invalid_parse", "protected_attribute_risk"]
ReasonerParseStatus = Literal[
    "valid",
    "source_failed",
    "missing_marker",
    "invalid_json",
    "invalid_schema",
    "invalid_label",
]


@dataclass(frozen=True)
class ReasonerOutputContract:
    """Prompt-level contract for parseable Reasoner model output."""

    labels: tuple[str, str, str]
    parse_marker: str
    fields: tuple[str, ...]
    evidence_types: tuple[EvidenceType, ...]


@dataclass(frozen=True)
class ReasonerPromptTemplate:
    """Versioned Reasoner prompt template loaded from configs/prompts."""

    version: str
    system_prompt: str
    user_template: str
    output_contract: ReasonerOutputContract
    evidence_types: tuple[EvidenceType, ...]
    forbidden_sole_support_cues: tuple[str, ...]


@dataclass(frozen=True)
class ReasonerPrompt:
    """Built prompt for one prediction sample."""

    sample_id: str
    prompt_version: str
    system_prompt: str
    user_prompt: str
    output_contract: ReasonerOutputContract


@dataclass(frozen=True)
class ReasonerOutput:
    """Schema-valid structured output generated by the Reasoner."""

    label: ReasonerLabel
    evidence: str
    evidence_type: EvidenceType
    uncertainty_signal: bool
    protected_attribute_risk: bool
    uncertainty_option_index: int
    schema_version: str


@dataclass(frozen=True)
class ParsedReasonerRecord:
    """One parsed Reasoner row, including invalid and source-failure states."""

    run_id: str
    sample_id: str
    parsed_label: ReasonerLabel | None
    evidence_summary: str | None
    evidence_type: EvidenceType | None
    uncertainty_signal: bool | None
    risk_flags: tuple[ReasonerRiskFlag, ...]
    parse_status: ReasonerParseStatus
    parse_error: str | None
    uncertainty_option_index: int | None = None
    schema_version: str | None = None


@dataclass(frozen=True)
class ReasonerParseResult:
    """Summary and ordered rows from parsing a raw Reasoner artifact."""

    parsed_reasoner_path: Path
    records: tuple[ParsedReasonerRecord, ...]
    total_samples: int
    valid_count: int
    invalid_count: int


@dataclass(frozen=True)
class VerifierOutputContract:
    """Prompt-level contract for parseable Verifier model output."""

    labels: tuple[str, str, str]
    parse_marker: str
    fields: tuple[str, ...]
    evidence_types: tuple[EvidenceType, ...]


@dataclass(frozen=True)
class VerifierPromptTemplate:
    """Versioned independent Verifier prompt template."""

    version: str
    system_prompt: str
    user_template: str
    output_contract: VerifierOutputContract
    evidence_types: tuple[EvidenceType, ...]
    forbidden_sole_support_cues: tuple[str, ...]


@dataclass(frozen=True)
class VerifierPrompt:
    """Built Verifier prompt for one triggered sample."""

    sample_id: str
    prompt_version: str
    system_prompt: str
    user_prompt: str
    output_contract: VerifierOutputContract


@dataclass(frozen=True)
class VerifierOutput:
    """Schema-valid structured output generated by the Verifier."""

    label: ReasonerLabel
    reason: str
    evidence_type: EvidenceType
    reasoner_defect_found: bool
    objective_support: bool


VerifierParseStatus = Literal[
    "valid",
    "missing_marker",
    "invalid_json",
    "invalid_schema",
    "invalid_label",
]


@dataclass(frozen=True)
class ParsedVerifierOutput:
    """Typed result of parsing one raw Verifier response."""

    output: VerifierOutput | None
    parse_status: VerifierParseStatus
    parse_error: str | None


VerificationTrigger = Literal[
    "invalid_parse",
    "low_confidence",
    "unsupported_evidence",
    "protected_attribute_risk",
    "appearance_only_reasoning",
    "ambiguous_visual_grounding",
    "reasoner_verifier_conflict",
]


@dataclass(frozen=True)
class VerificationTriggerDecision:
    """Per-sample decision about whether conditional verification is needed."""

    run_id: str
    sample_id: str
    parsed_label: ReasonerLabel | None
    parse_status: ReasonerParseStatus
    triggers: tuple[VerificationTrigger, ...]
    requires_verification: bool


@dataclass(frozen=True)
class VerificationTriggerReport:
    """Ordered trigger decisions plus aggregate trigger counts."""

    decisions: tuple[VerificationTriggerDecision, ...]
    total_samples: int
    triggered_sample_count: int
    per_trigger_counts: Mapping[VerificationTrigger, int]

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "per_trigger_counts",
            MappingProxyType(dict(self.per_trigger_counts)),
        )


VerificationStatus = Literal[
    "verified",
    "skipped_not_triggered",
    "image_failed",
    "prompt_failed",
    "inference_failed",
    "parse_failed",
]


@dataclass(frozen=True)
class VerificationRecord:
    """One auditable conditional-Verifier outcome."""

    run_id: str
    sample_id: str
    prompt_version: str
    triggers: tuple[VerificationTrigger, ...]
    requires_verification: bool
    before_label: ReasonerLabel | None
    raw_verifier_output: str | None
    after_label: ReasonerLabel | None
    verifier_reason: str | None
    verifier_evidence_type: EvidenceType | None
    reasoner_defect_found: bool | None
    objective_support: bool | None
    image_status: ImageLoadStatus | None
    verifier_parse_status: VerifierParseStatus | None
    generation_metadata: ModelGenerationMetadata | None
    model_load_metadata: ModelLoadMetadata | None
    elapsed_seconds: float
    status: VerificationStatus
    error_type: str | None
    error_message: str | None


@dataclass(frozen=True)
class VerifierRunResult:
    """Summary and ordered rows from one conditional-Verifier run."""

    verification_path: Path
    records: tuple[VerificationRecord, ...]
    total_samples: int
    triggered_count: int
    verified_count: int
    skipped_count: int
    failed_count: int


FinalSourceStage = Literal["reasoner", "verifier", "arbitration"]


@dataclass(frozen=True)
class FinalPrediction:
    """One validated final label with its pipeline decision lineage."""

    run_id: str
    sample_id: str
    final_label: ReasonerLabel
    source_stage: FinalSourceStage
    decision_reason: str


@dataclass(frozen=True)
class SubmissionResult:
    """Completed final-prediction and Multimodal submission artifacts."""

    final_predictions_path: Path
    submission_path: Path
    predictions: tuple[FinalPrediction, ...]
    total_samples: int


ModelAdapterType = Literal["dummy", "hf_local", "minicpm_v"]
ModelLoadStatus = Literal["not_loaded", "loaded", "failed"]


@dataclass(frozen=True)
class ModelConfig:
    """Validated local model adapter configuration."""

    config_path: Path
    adapter: ModelAdapterType
    model_name: str
    snapshot_path: Path
    revision: str
    snapshot_hash: str
    local_files_only: bool
    trust_remote_code: bool
    device_map: str
    torch_dtype: str
    max_new_tokens: int
    do_sample: bool
    model_class: str = "AutoModelForImageTextToText"


@dataclass(frozen=True)
class ModelLoadMetadata:
    """Audit metadata from loading a local model adapter."""

    model_name: str
    adapter: ModelAdapterType
    snapshot_path: Path
    revision: str
    snapshot_hash: str
    local_files_only: bool
    trust_remote_code: bool
    load_status: ModelLoadStatus
    device: str | None
    torch_dtype: str | None
    message: str | None = None


@dataclass(frozen=True)
class ModelGenerationRequest:
    """One local model generation request."""

    prompt_text: str
    image_path: Path | None = None
    image_bytes: bytes | None = None
    image_format: str | None = None
    max_new_tokens: int | None = None


@dataclass(frozen=True)
class ModelGenerationMetadata:
    """Metadata describing one model generation call."""

    adapter: ModelAdapterType
    model_name: str
    max_new_tokens: int
    do_sample: bool
    elapsed_seconds: float
    input_token_count: int | None = None
    output_token_count: int | None = None
    device: str | None = None
    torch_dtype: str | None = None


@dataclass(frozen=True)
class ModelGenerationResult:
    """Raw generated model text and metadata."""

    raw_text: str
    metadata: ModelGenerationMetadata


@dataclass(frozen=True)
class CompetitionConfig:
    """Resolved runtime configuration for local pipeline commands."""

    data_root: Path
    runs_root: Path
    run_name: str


@dataclass(frozen=True)
class RunManifest:
    """Created run directory and required metadata artifact paths."""

    run_id: str
    run_dir: Path
    config_path: Path
    resolved_config_path: Path
    environment_path: Path
    created_at_utc: str


ImageLoadStatus = Literal["loaded", "missing", "unreadable", "corrupt"]
ImageFormat = Literal["jpeg", "png", "gif", "webp"]


@dataclass(frozen=True)
class ImageLoadResult:
    """Per-sample image IO result for inference inputs."""

    sample_id: str
    image_path: Path
    status: ImageLoadStatus
    image_bytes: bytes | None
    image_format: ImageFormat | None
    error_message: str | None


@dataclass(frozen=True)
class ImageLoadReport:
    """Ordered image IO results plus aggregate counts."""

    results: tuple[ImageLoadResult, ...]

    @property
    def success_count(self) -> int:
        return sum(result.status == "loaded" for result in self.results)

    @property
    def failure_count(self) -> int:
        return len(self.results) - self.success_count


RawReasonerStatus = Literal["generated", "image_failed", "prompt_failed", "inference_failed"]


@dataclass(frozen=True)
class RawReasonerRecord:
    """One raw Reasoner JSONL row before parsing or final label selection."""

    run_id: str
    sample_id: str
    prompt_version: str | None
    prompt_text: str | None
    prompt_sha256: str | None
    image_path: Path
    image_status: ImageLoadStatus
    image_sha256: str | None
    image_byte_count: int | None
    image_format: ImageFormat | None
    raw_output: str | None
    generation_metadata: ModelGenerationMetadata | None
    model_load_metadata: ModelLoadMetadata
    elapsed_seconds: float
    status: RawReasonerStatus
    error_type: str | None
    error_message: str | None


@dataclass(frozen=True)
class ReasonerRunResult:
    """Summary of a raw Reasoner inference run."""

    manifest: RunManifest
    raw_reasoner_path: Path
    total_samples: int
    generated_count: int
    failure_count: int


@dataclass(frozen=True)
class CandidateManifest:
    """Pinned offline eligibility evidence for one tournament candidate."""

    candidate_id: str
    official_repo: str
    commit: str
    release_date: str
    cutoff_evidence: str
    license_id: str
    license_url: str
    snapshot_sha256: str
    custom_code_hashes: tuple[tuple[str, str], ...]
    dependency_lock_path: Path
    processor_evidence: str
    chat_template_evidence: str
    image_serialization_evidence: str
    preprocessing_metadata: tuple[tuple[str, str], ...]
    remote_api_usage: str


@dataclass(frozen=True)
class CandidateHardwareTelemetry:
    """GPU identity and memory measurements captured during candidate smoke."""

    gpu_name: str | None
    total_vram_mib: int | None
    peak_vram_mib: int | None


@dataclass(frozen=True)
class CandidateRejection:
    """Stable machine-readable reason blocking diagnostic eligibility."""

    code: str
    detail: str


@dataclass(frozen=True)
class CandidateRenderedInputEvidence:
    """Hashes and declared official serialization path used for one smoke."""

    prompt_version: str
    prompt_sha256: str
    image_sha256: str
    processor_evidence: str
    chat_template_evidence: str
    image_serialization_evidence: str
    preprocessing_metadata: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class CandidateSmokeReport:
    """Eligibility and real-image structured-smoke result."""

    candidate_id: str
    manifest: CandidateManifest
    load_metadata: ModelLoadMetadata | None
    generation_metadata: ModelGenerationMetadata | None
    rendered_input: CandidateRenderedInputEvidence | None
    hardware: CandidateHardwareTelemetry
    raw_output: str | None
    parsed_label: ReasonerLabel | None
    uncertainty_option_index: int | None
    schema_version: str | None
    latency_seconds: float | None
    rejections: tuple[CandidateRejection, ...]
    diagnostic_48_allowed: bool
